name: Update TEE drivers
on:
  workflow_dispatch:
    inputs:
      direct_url:
        description: 'Direct URL to the file'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - uses: actions/checkout@v4 # Reverted to v4 unless you have a custom/future internal v6 setup

    - name: Configure Git Safe Directory
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Fetch system dependencies
      continue-on-error: false
      run: |
        sudo apt update -y
        sudo apt install -y unzip lz4 simg2img wget erofs-utils python3-pip python3 lpunpack

    - name: Check storage status
      run: df -h

    - name: Check current directory
      run: ls -laZ

    - name: Copy tools into bin
      run: cd ${{ github.workspace }}/tools && chmod +x * && sudo cp -r * /usr/local/bin/

    - name: Fetch TEE drivers
      run: bash scripts/fetch.sh "${{ github.event.inputs.direct_url }}"
      working-directory: ${{ github.workspace }}

    - name: Update directory
      run: python3 scripts/gen.py
      working-directory: ${{ github.workspace }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "a05m-tee: Update TEE drivers"
        committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        branch: "update-tee-drivers" # DO NOT target "main" here. This is the new HEAD branch for the PR.
        base: "main" # The branch you want to merge into
        title: "a05m-tee: Update TEE drivers"
        body: |
          Automated TEE driver update via workflow dispatch.
        labels: automated-pr